### ISSUE TITLE
BindingResolutionException when including version 3.2

### ISSUE THREAD

**Issue by webwisejordan** [nordsoftware/lumen-cors#75]
I had a previous version of lumen-cors installed previously and had to remove it when upgrading to Lumen 6 because that version didn't support it.  I just added the new version back to my lumen app and I get the following error:

"Target [Nord\\Lumen\\Cors\\Contracts\\CorsService] is not instantiable while building [Nord\\Lumen\\Cors\\CorsMiddleware]."  (full stack trace below).

The steps I took were:
1. `composer require nordsoftware/lumen-cors`
2. Add cors.php to /config
3. Add `$app->configure('cors');` to boostrap/app.php
4. Add
```
$app->middleware([
    Nord\Lumen\Cors\CorsMiddleware::class
]);
```
to bootstrap/app.php

My composer.json looks like this:

```{
    "name": "laravel/lumen",
    "description": "The Laravel Lumen Framework.",
    "keywords": ["framework", "laravel", "lumen"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.2",
        "laravel/lumen-framework": "6.2.*",
        "vlucas/phpdotenv": "^3.3.1",
        "laravel-doctrine/orm": "1.5.4",
        "laravel-doctrine/extensions": "1.1.*",
        "dingo/api": "2.4.0",
        "gedmo/doctrine-extensions": "^2.4",
        "nuwave/lighthouse": "4.7.*",
        "nordsoftware/lumen-cors": "^3.2"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "phpunit/phpunit": "~8.0",
        "mockery/mockery": "~1.0",
        "phpmd/phpmd" : "^2.7",
        "squizlabs/php_codesniffer": "^3.5",
        "maglnet/composer-require-checker": "^2.0",
        "sebastian/phpcpd": "^4.1",
        "jakub-onderka/php-parallel-lint": "^1.0",
        "povils/phpmnd": "^2.1",
        "phpstan/phpstan": "^0.12.3",
        "vimeo/psalm": "^3.7",
        "sensiolabs/security-checker": "^6.0",
        "phpro/grumphp": "^0.17.0",
        "phpstan/phpstan-doctrine": "^0.12.9",
        "phpstan/extension-installer": "^1.0"
    },
    "autoload": {
        "classmap": [
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/",
            "database/"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Stack Trace**
```
 "#0 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/container\/Container.php(812): Illuminate\\Container\\Container->notInstantiable('Nord\\\\Lumen\\\\Cors...')",
      "#1 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/container\/Container.php(681): Illuminate\\Container\\Container->build('Nord\\\\Lumen\\\\Cors...')",
      "#2 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/container\/Container.php(629): Illuminate\\Container\\Container->resolve('Nord\\\\Lumen\\\\Cors...', Array)",
      "#3 \/home\/jordan\/www\/spidersmart-api\/vendor\/laravel\/lumen-framework\/src\/Application.php(267): Illuminate\\Container\\Container->make('Nord\\\\Lumen\\\\Cors...', Array)",
      "#4 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/container\/Container.php(945): Laravel\\Lumen\\Application->make('Nord\\\\Lumen\\\\Cors...')",
      "#5 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/container\/Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))",
      "#6 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/container\/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)",
      "#7 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/container\/Container.php(681): Illuminate\\Container\\Container->build('Nord\\\\Lumen\\\\Cors...')",
      "#8 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/container\/Container.php(629): Illuminate\\Container\\Container->resolve('Nord\\\\Lumen\\\\Cors...', Array)",
      "#9 \/home\/jordan\/www\/spidersmart-api\/vendor\/laravel\/lumen-framework\/src\/Application.php(267): Illuminate\\Container\\Container->make('Nord\\\\Lumen\\\\Cors...', Array)",
      "#10 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/pipeline\/Pipeline.php(160): Laravel\\Lumen\\Application->make('Nord\\\\Lumen\\\\Cors...')",
      "#11 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/pipeline\/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
      "#12 \/home\/jordan\/www\/spidersmart-api\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#13 \/home\/jordan\/www\/spidersmart-api\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
      "#14 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/pipeline\/Pipeline.php(171): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
      "#15 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
      "#16 \/home\/jordan\/www\/spidersmart-api\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(32): call_user_func(Object(Closure), Object(Laravel\\Lumen\\Http\\Request))",
      "#17 \/home\/jordan\/www\/spidersmart-api\/vendor\/illuminate\/pipeline\/Pipeline.php(105): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))",
      "#18 \/home\/jordan\/www\/spidersmart-api\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(413): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
      "#19 \/home\/jordan\/www\/spidersmart-api\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(171): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))",
      "#20 \/home\/jordan\/www\/spidersmart-api\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(108): Laravel\\Lumen\\Application->dispatch(NULL)",
      "#21 \/home\/jordan\/www\/spidersmart-api\/public\/index.php(29): Laravel\\Lumen\\Application->run()",
      "#22 {main}"
```

Thank you for looking

**Comment by webwisejordan** [comment]
Sorry, seems I was missing registering the service provider with app->register() thereby causing the problem.
