### ISSUE TITLE
Nord\Lumen\Cors\CorsService::__construct(): Argument #1 ($config) must be of type array, null given

### ISSUE THREAD

**Issue by Ahmard** [nordsoftware/lumen-cors#87]
### What did you do?
Trying the package out
### What did you expect to happen?
To work fine
### What actually happened?
Throws an error
### What versions of PHP, Lumen and this module are you using?
PHP 8.0, Lumen 9
Please include code that reproduces the issue. The best reproductions are self-contained scripts with minimal dependencies.

```
[2022-03-27 21:01:13] local.ERROR: Nord\Lumen\Cors\CorsService::__construct(): Argument #1 ($config) must be of type array, null given, called in PROJECT_DIR/vendor/nordsoftware/lumen-cors/src/CorsServiceProvider.php on line 33 {"exception":"[object] (TypeError(code: 0): Nord\\Lumen\\Cors\\CorsService::__construct(): Argument #1 ($config) must be of type array, null given, called in PROJECT_DIR/vendor/nordsoftware/lumen-cors/src/CorsServiceProvider.php on line 33 at PROJECT_DIR/vendor/nordsoftware/lumen-cors/src/CorsService.php:59)
[stacktrace]
#0 PROJECT_DIR/vendor/nordsoftware/lumen-cors/src/CorsServiceProvider.php(33): Nord\\Lumen\\Cors\\CorsService->__construct()
#1 PROJECT_DIR/vendor/illuminate/container/Container.php(873): Nord\\Lumen\\Cors\\CorsServiceProvider->Nord\\Lumen\\Cors\\{closure}()
#2 PROJECT_DIR/vendor/illuminate/container/Container.php(758): Illuminate\\Container\\Container->build()
#3 PROJECT_DIR/vendor/illuminate/container/Container.php(694): Illuminate\\Container\\Container->resolve()
#4 PROJECT_DIR/vendor/laravel/lumen-framework/src/Application.php(300): Illuminate\\Container\\Container->make()
#5 PROJECT_DIR/vendor/illuminate/container/Container.php(1027): Laravel\\Lumen\\Application->make()
#6 PROJECT_DIR/vendor/illuminate/container/Container.php(947): Illuminate\\Container\\Container->resolveClass()
#7 PROJECT_DIR/vendor/illuminate/container/Container.php(908): Illuminate\\Container\\Container->resolveDependencies()
#8 PROJECT_DIR/vendor/illuminate/container/Container.php(758): Illuminate\\Container\\Container->build()
#9 PROJECT_DIR/vendor/illuminate/container/Container.php(694): Illuminate\\Container\\Container->resolve()
#10 PROJECT_DIR/vendor/laravel/lumen-framework/src/Application.php(300): Illuminate\\Container\\Container->make()
#11 PROJECT_DIR/vendor/illuminate/pipeline/Pipeline.php(169): Laravel\\Lumen\\Application->make()
#12 PROJECT_DIR/vendor/laravel/lumen-framework/src/Routing/Pipeline.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 PROJECT_DIR/vendor/illuminate/pipeline/Pipeline.php(116): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}()
#14 PROJECT_DIR/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(426): Illuminate\\Pipeline\\Pipeline->then()
#15 PROJECT_DIR/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(175): Laravel\\Lumen\\Application->sendThroughPipeline()
#16 PROJECT_DIR/vendor/laravel/lumen-framework/src/Concerns/RoutesRequests.php(112): Laravel\\Lumen\\Application->dispatch()
#17 PROJECT_DIR/public/index.php(28): Laravel\\Lumen\\Application->run()
#18 {main}
"}
```

**Comment by Jalle19** [comment]
Did you perhaps miss this step:
> Copy the configuration template in config/cors.php to your application's config directory and modify according to your needs

**Comment by leasafricgh** [comment]
> Did you perhaps miss this step:
> 
> > Copy the configuration template in config/cors.php to your application's config directory and modify according to your needs

I did copy it

**Comment by Ahmard** [comment]
Already did

**Comment by Jalle19** [comment]
Are you sure? The error happens if you don't have the configuration file in place.

**Comment by Ahmard** [comment]
Fixed, thanks for your time.

**Comment by krystianlaubach** [comment]
I've got the same exception from CorsServiceProvider

```
2022-05-11 13:08:45.923 EEST[11-May-2022 10:08:45] WARNING: [pool www] child 11 said into stderr: "[2022-05-11 10:08:45] local.ERROR: Argument 1 passed to Nord\Lumen\Cors\CorsService::__construct() must be of the type array, null given, called in /var/www/html/vendor/nordsoftware/lumen-cors/src/CorsServiceProvider.php on line 33 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Nord\\Lumen\\Cors\\CorsService::__construct() must be of the type array, null given, called in /var/www/html/vendor/nordsoftware/lumen-cors/src/CorsServiceProvider.php on line 33 at /var/www/html/vendor/nordsoftware/lumen-cors/src/CorsService.php:59)"
```

I have added config file into correct place `config\cors.php` but for some reason it doesn't see it 🤔 

![image](https://user-images.githubusercontent.com/43027835/167831667-8e1e9092-e47b-416e-83ea-2db192e453b2.png)
